<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MUNI-VAIO" name="Test1" tests="3" failures="2" timestamp="14 Jan 2019 06:59:18 GMT" time="138.356" errors="0">
  <testcase name="testValidLogin" time="53.424" classname="script.TestValidLogin">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at page.LoginPage.verifyTitle(LoginPage.java:65)
	at script.TestValidLogin.testValidLogin(TestValidLogin.java:36)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testValidLogin -->
  <testcase name="testInvalidLogin" time="3.317" classname="script.TestInvalidLogin"/>
  <testcase name="testVerifyProductVersion" time="50.94" classname="script.TestVerifyProductVersion">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at generic.WebGeneric.verifyTitle(WebGeneric.java:20)
	at script.TestVerifyProductVersion.testVerifyProductVersion(TestVerifyProductVersion.java:31)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testVerifyProductVersion -->
</testsuite> <!-- Test1 -->
